### ISSUE TITLE
[feature]: sources.adguard seems to be missing?

### ISSUE THREAD

**Issue by ping-localhost** [T145/black-mirror#119]
### What happened?

It seems that [during a refactor](https://github.com/T145/black-mirror/commit/e0e174005ecdcc0cfa52b5ac07c5deb9815abfe5) `sources.adguard` has been removed? Did it get moved or is the README.md no longer up to date? 😅 

Sorry for opening this as a bug report, but it seemed like the closest valid option. Thank you for keeping this list up-to-date!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by T145** [comment]
Yes it was removed and the README wasn't updated. This was mostly b/c I didn't know if it was a feature people liked as there hasn't been too much regarding community feedback. The infrastructure to generate it is still present though, so if you download the manifest just do:
```bash
jq -jr 'to_entries[] | select(.value.method == "BLOCK" and .value.variants.adguard != null) | ("!#include ", .value.variants.adguard, "\n")' "manifest.json" >sources.adguard
```
Is this something you'd be interested in having as a build product?

**Comment by ping-localhost** [comment]
I think it could be useful for new users, yeah. That said, I've already added all the URLs separately, so I no longer need it 😅
