### ISSUE TITLE
[bug]: Minor Awk regex bug when processsing schakal

### ISSUE THREAD

**Issue by T145** [T145/black-mirror#190]
### What happened?

The following command:
```
mawk '$1~/^(0.0.0.0|127.0.0.1|0|::)$/&&$2!~/^(localhost|local|localhost.localdomain)$/{print $2}' alive_hosts.txt | head
```
Performed on the [`schakal`](https://schakal.ru/hosts/alive_hosts.txt) list prints the given output, when the "localhost" is not expected to be included.

What's confusing is the `127.0.0.1 localhost` entry isn't ignored, but in other lists that use that same statement (like [KodoPenguin's GameIndustry list](https://raw.githubusercontent.com/KodoPengin/GameIndustry-hosts-Template/master/Main-Template/hosts)) it is.

This regex works on all other hosts files, so again this is strange. Maybe an issue with line endings?

### Operating System

Debian Bookworm

### Relevant log output

```bash
localhost
0-02pw.cfd
0-2lyb.sbs
0-47pc.cfd
0-6n10.sbs
0-84-4a0455e3-22d8-4d50-afd7-8f5cf0f75e65.analytics.mobilegamestats.com
0-9m4v.sbs
0-avn0.sbs
0-finanzierung.com
0-okodukai.com
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jarelllama** [comment]
Seems to be the carriage return characters (had to use awk here since I'm testing this on a mobile emulator)

``` console
$ awk '$1~/^(0.0.0.0|127.0.0.1|0|::)$/&&$2!~/^(localhost|local|localhost.localdomain)$/{print $2}' a | grep localhost
localhost
localhost.store.pay.florencerepairs.com
nlocalhost.wordtheminer.com
www.localhost.store.pay.florencerepairs.com

$ sed -i 's/\r//g' a
$ awk '$1~/^(0.0.0.0|127.0.0.1|0|::)$/&&$2!~/^(localhost|local|localhost.localdomain)$/{print $2}' a | grep localhost
localhost.store.pay.florencerepairs.com
nlocalhost.wordtheminer.com
www.localhost.store.pay.florencerepairs.com
```

**Comment by T145** [comment]
Thanks for verifying! A quick `sub(/\r$/, "")` should fix it then.
