### ISSUE TITLE
[bug]: Youtube is blocked

### ISSUE THREAD

**Issue by AyanokojiK1yotaka** [T145/black-mirror#191]
### What happened?

A bug happened!

### Operating System

pihole 

### Relevant log output

```bash
.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by T145** [comment]
Thanks! Should be fixed tomorrow. If you run across any more, feel free to make a PR to this file:
https://github.com/T145/black-mirror/blob/master/data/v2/contrib/DOMAIN_WHITELIST.txt
