### ISSUE TITLE
https://assets.windscribe.com/extension/ws/malwaredomains.txt

### ISSUE THREAD

**Issue by badmojr** [T145/black-mirror#50]
Originally reported:
https://github.com/badmojr/1Hosts/issues/171#issuecomment-867652823

Hope you find it useful.
Cheers!

**Comment by T145** [comment]
```
! Title: WindscribeMalwareList
! Updated: Wed, 19 May 2021 12:13:05 UTC
! Expires: 1 day (update frequency)
! Homepage: https://gitlab.com/curben/urlhaus-filter
! License: https://gitlab.com/curben/urlhaus-filter#license
! Source: https://urlhaus.abuse.ch/api/
```
I'm using all the full/aggressive abuse.ch lists, so this is redundant. I'll investigate the endpoint though; thanks!
Also, I've started a discussion on this topic for tips and more casual discussion: https://github.com/T145/the-blacklist/discussions/48
